_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        [[ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
           0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
           0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
           0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
           0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
           0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
           0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
           0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
           0.0000000e+00  0.0000000e+00  0.0000000e+00 -1.6625843e-05
          -1.8356838e-04  7.0618456e-03  7.0534297e-04  2.0997298e-04]]
_last_original_obs:
    value: '[[-0.00166275 -0.01836177  0.99749637  0.07071748  0.02100403]]'
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x7f0f4dd09fd0>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 500000
_vec_normalize_env:
    value: <stable_baselines3.common.vec_env.vec_normalize.VecNormalize object at 0x7f0f74752840>
_wandb:
    value:
        cli_version: 0.26.0
        code_path: code/AI/train_agent.py
        e:
            qdeykui9ogx0eccnnwiwbkfrz1867yt4:
                codePath: AI/train_agent.py
                codePathLocal: AI/train_agent.py
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "153174614016"
                        used: "52889952256"
                email: minhnguyen20042111@gmail.com
                executable: /home/cat21/mujoco_env/bin/python
                git:
                    commit: 066447d9de4712fe1f5f733272e4b8bfb062c560
                    remote: https://github.com/cat2I/simulation-code.git
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 2560
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-c214715e-1adb-4d58-4792-06a1c0f4d7ef
                host: cat21-IdeaPad-Pro-5-16IRH8
                memory:
                    total: "16490975232"
                os: Linux-6.17.0-20-generic-x86_64-with-glibc2.39
                program: /home/cat21/Documents/lab/simulation&code/AI/train_agent.py
                python: CPython 3.12.3
                root: /home/cat21/Documents/lab/simulation&code
                startedAt: "2026-04-18T09:43:00.839261Z"
                writerId: qdeykui9ogx0eccnnwiwbkfrz1867yt4
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
                - 22
                - 35
                - 41
            "4": 3.12.3
            "5": 0.26.0
            "12": 0.26.0
            "13": linux-x86_64
action_noise:
    value: None
action_space:
    value: Box(-1.0, 1.0, (1,), float32)
algo:
    value: PPO
architecture:
    value: 128x128
batch_size:
    value: 64
clip_range:
    value: FloatSchedule(ConstantSchedule(val=0.2))
clip_range_vf:
    value: None
device:
    value: cpu
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.vec_frame_stack.VecFrameStack object at 0x7f0f7475d940>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
lr_schedule:
    value: FloatSchedule(<function linear_schedule.<locals>.func at 0x7f0f746d49a0>)
max_grad_norm:
    value: 0.5
n_envs:
    value: 1
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: |-
        Box([ -5.  -5.  -5.  -5.  -5.  -5.  -5.  -5. -50. -50. -50. -50. -50. -50.
         -50. -50.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.
          -1.  -1.  -1.  -1. -50. -50. -50. -50. -50. -50. -50. -50.], [ 5.  5.  5.  5.  5.  5.  5.  5. 50. 50. 50. 50. 50. 50. 50. 50.  1.  1.
          1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. 50. 50. 50. 50.
         50. 50. 50. 50.], (40,), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=40, out_features=128, bias=True)
              (1): Tanh()
              (2): Linear(in_features=128, out_features=128, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=40, out_features=128, bias=True)
              (1): Tanh()
              (2): Linear(in_features=128, out_features=128, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=128, out_features=1, bias=True)
          (value_net): Linear(in_features=128, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{''activation_fn'': <class ''torch.nn.modules.activation.Tanh''>, ''net_arch'': {''pi'': [128, 128], ''vf'': [128, 128]}}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7f0f74497b00>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1776505384883308532
target_kl:
    value: 0.015
tensorboard_log:
    value: ./tensorboard/tensorboard_logs/
total_timesteps:
    value: 500000
use_sde:
    value: "False"
verbose:
    value: 0
vf_coef:
    value: 0.5
